Repository Team-HAGOJAEBI/diground-fe, pull requests merged in 2025-08, with the labels that each got.

#35 feat: 소셜로그인 구현(카카오)
  .gitignore
  eslint.config.mjs
  next.config.ts
  package.json
  pnpm-lock.yaml
  src/app/_common/icon/Icon.tsx
  src/app/login/kakao/api/login.ts
  src/app/login/kakao/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/assets/icons/ic_kakao_login.png
  src/assets/icons/index.ts
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/sample/User.ts
Labels: ✨ Feature

#30 5. [create] create 화면 추가
  src/app/create/page.tsx
Labels: ✨ Feature, 🎨 Html&css

#61 chore: copilot-instructions.md 추가
  .github/copilot-instructions.md
Labels: ⚙ Setting
